### ISSUE TITLE
Compatibility issue with controlpack (liteloader mod)

### ISSUE THREAD

**Issue by guiguilyon** [mod-warriors/NotEnoughKeys#27] opened 2015-01-23 04:19 UTC
Hi. 

Whenever NEK is enabled (in Feed The Beast Direwolf 1.7.10 modpack), several controlpack features don't work anymore. More specifically, the Toggle Sneak, Auto Jump, Auto Run, Toggle Mining, Toggle Use Item and Run Distance features don't work.

This is controlpack by infinitiesloop, that you can find here : http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1274134-controlpack-autosneak-run-autotool-smartfurnace

Even if I only enable both NEK and controlpack, it still doesn't work.

Is that related to the fact that NEK overrides LiteLoader's keybinds gui as Mr_okushama was saying December 10, 2013 here : http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292963-not-enough-keys-making-pressing-buttons-easier?comment=26

Thanks

**Comment by dmodoomsirius** [comment] 2015-01-23 12:46
What version of NotEnoughKeys is in the Direwolf20 Modpack?

**Comment by guiguilyon** [comment] 2015-01-23 15:18
This is the version 1.0.0b29 as mentioned in the officicial changelog here : https://feedthebeast.atlassian.net/wiki/display/PML/Direwolf20+%281.7.x%29+1.0.3

But I would be surprised that it is related to the pack, since the issue remains even when every other mod but controlepack and NEK are disabled.

**Comment by TheTemportalist** [comment] 2015-01-23 15:44
It is most likely a controlpack issue. Is the mod opensource? If so, I can peak at the code

**Comment by guiguilyon** [comment] 2015-01-23 16:28
It doesn't seem to be open source. Someone suggested that it should be, here : http://mccontrolpack.uservoice.com/forums/131141-general/suggestions/5852349-make-the-source-public-so-people-can-update-it,  but didn't get any response.

**Comment by TheTemportalist** [comment] 2015-01-23 20:21
Not much I can do then. Did you tell their mod authors?

**Comment by guiguilyon** [comment] 2015-01-23 20:46
Yea, I told controlpack author in its thread from post #2650 here : http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1274134-controlpack-autosneak-run-autotool-smartfurnace?comment=2651

**Comment by guiguilyon** [comment] 2015-02-04 15:58
Any news ?

**Comment by guiguilyon** [comment] 2015-04-17 11:50
Still nothing ?

**Comment by TheTemportalist** [comment] 2015-04-17 17:55
err... ummm. yeah. sorry. Busy with so many things ATM. Let alone MC modding and backporting and so many things. thats why I have other people here. @dmodoomsirius: Can you do some Public Relations for me? The author is on their own irc somewhere (not espernet). I dont have time these days.

**Comment by uyjulian** [comment] 2015-04-18 15:01
I'm uyjulian on freenode and efnet.

**Comment by dmodoomsirius** [comment] 2015-04-18 15:31
Commenting so i don't lose src code https://github.com/uyjulian/ControlPack

**Comment by Parker8283** [comment] 2015-04-18 15:38
We don't override Liteloader keybinds anymore, so that can't be it. I suspect it's something on the other mod devs side.

**Comment by uyjulian** [comment] 2015-04-18 15:45
My issue should have been fixed already, I should not override the keybinds gui anymore...

**Comment by Parker8283** [comment] 2015-04-18 15:46
in 1.7 or 1.8? Because the issue is occurring in 1.7.

**Comment by uyjulian** [comment] 2015-04-18 15:48
1.8.
The issue is occurring in 1.7 'cause I didn't register all my keys properly. I do that in 1.8.

**Comment by Parker8283** [comment] 2015-04-18 15:49
Anyways, this isn't our problem. It's up to @uyjulian to potentially fix for 1.7. Closing.

**Closed by Parker8283** 2015-04-18 15:49 UTC

**Comment by TheTemportalist** [comment] 2015-04-18 21:51
Glad someone else fixed this issue for me :)
